/*
 * ALUNO: ARTHUR MENDES LUCAS
 * CURSO: ANÁLISE E DESENVOLVIMENTO DE SISTEMAS
 * PERÍODO: SEGUNDO TRIMESTRE
 * FACULDADE: PONTIFÍCIA UNIVERSIDADE CATÓLICA DO PARANÁ
 */

package util;
    //AQUI EU ESTOU VERIFICANDO POR MEIO DE UMA EXCEPTION, SE O DESCONTO FORNECIDO PELO USUÁRIO É SUPERIOR A MENSALIDADE PAGA, SE FOR, ELA SERÁ DESCONSIDERADA E O USUÁRIO TERÁ QUE INFORMAR UM DESCONTO INFERIOR A MENSALIDADE.
public class DescontoMaiorDoQueJurosException extends Exception {
    public DescontoMaiorDoQueJurosException(String mensagem) {
        super(mensagem);
    }
}